server:
  port: "8400"
  
mongo:
    host: "mongodb+srv://zones-user:43Z8Rq26L9S5cFy0@db-mongodb-nyc1-71962-6157d0c7.mongo.ondigitalocean.com/zones-db?tls=true&authSource=admin&replicaSet=db-mongodb-nyc1-71962"
    port: "27017"
    
spring:
    data:
        mongodb:
          port: ${mongo.port}
          uri: ${mongo.host}
